### ISSUE TITLE
Use SWIG to build from source

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-spams-feedstock#12]
Some of the problems we have building this package like NumPy support and handling Python 2/3 simply are caused by the fact that we use tarballs generated by the developers with SWIG and other things. If we directly built from source using SWIG, we should be able to avoid all of these issues and avoid some patching of our own. As such we should switch to use the original source with SWIG to build this package directly.

**Comment by zym1010** [comment]
maybe not relevant anymore?

**Comment by jakirkham** [comment]
Not relevant as the code no longer uses SWIG.
