### ISSUE TITLE
new spams 2.6.1

### ISSUE THREAD

**Issue by zym1010** [conda-forge/python-spams-feedstock#17]
on INRIA site, there's a new 2.6 version, on April 18.

I'd like to update the feedstock to this version, as it deprecates some of your patches.

But how should I set the version? Currently, it's only `2.6`. I want to differentiate two versions of 2.6.

**Comment by jakirkham** [comment]
Could you please ask them to mark it as 2.6.1? Seems silly to have two things called 2.6.

**Comment by zym1010** [comment]
@jakirkham  alright.

**Comment by zym1010** [comment]
@jakirkham the maintainer of spams told me we can access <https://gforge.inria.fr/frs/?group_id=3975> and find the full version strings (with dates) for all the spams versions. He think it would be easy for us to get a one-to-one correspondence using that. Would that be ok?

**Comment by zym1010** [comment]
> Hi,
>
> you can have access to all the releases here: 
> https://gforge.inria.fr/frs/?group_id=3975
> while I cannot change the names of all these files there, we should be able to easily make a one-to-one correspondence between the  2.6-date  with 2.6.x from this list.  Would that help?
> 
> Cheers.
> 
> Julien

**Comment by zym1010** [comment]
@jakirkham any feedback?

**Comment by jakirkham** [comment]
Sorry been occupied with other things of late. Given he can't change the existing files, could he push a new one that says 2.6.1?

**Comment by zym1010** [comment]
@jakirkham I will ask him.

**Comment by jakirkham** [comment]
Just as a note, also emailed about this issue yesterday. As another note, this release was not made only for Python 3 (not Python 2).

**Comment by jakirkham** [comment]
There has since been a 2.6.1 release. So am updating this issue to point to 2.6.1 instead.

**Comment by zym1010** [comment]
thanks @jakirkham . I will work on it after a paper deadline early next month.
